FROM golang:1.9.2-alpine as server
WORKDIR /go/src/github.com/Stratoscale/logserver
COPY . .
RUN go build -o /logserver
RUN go build -o /logstack ./logstack/

FROM alpine:3.7
COPY --from=server /logserver /usr/bin/logserver
COPY --from=server /logstack /usr/bin/logstack
COPY ./client/dist /client/dist
ENTRYPOINT ["logserver"]
